#ifndef lge.h
#define lge.h

#include lge.h

#define CONFIG_NR_DRAM_BANKS 1
#define CONFIG_SYS_MAX_FLASH_BANKS 1
#define CONFIG_SYS_MALLOC_LEN 0x2000
#define CONFIG_SYS_FSL_ESDHC_ADDR 0
#define CONFIG_PHYS_SDRAM 0x100000000
#define CONFIG_SYS_SDRAM_BASE 0x40000000
#define CONFIG_SYS_INIT_RAM_ADDR 0x40000000
#define CONFIG_SYS_INIT_EAM_SIZE 0x40000000
#define CONFIG_SYS_INIT_SP_OFFSET \
  (CONFIG_SYS_INIT_RAM_ADDR - GENERATED_GBL_DATA_SIZE)

#define CONFIG_SYS_INIT_SP_ADDR \
  (CONFIG_SYS_INIT_RAM_ADDR + CONFIG_SYS_INIT_SP_OFFSET)
#endif
